import util from 'util'

export default {
  name: 'CRM',
  command: ['crm'],
  category: 'developer',
  description: 'Generate relay code dari quoted message payload (owner only)',
  ownerOnly: true,
  cooldown: 1000,

  async execute({ sock, m, chat, quoted }) {
    if (!quoted) {
      await sock.sendMessage(chat, {
        text: '*[ CRM ]*\n\nReply ke pesan yang mau di-generate relay code-nya, lalu ketik crm',
      }, { quoted: m })
      return
    }

    const targetMessage = quoted.message
    if (!targetMessage) {
      await sock.sendMessage(chat, { text: 'Gagal ambil payload. Format tidak didukung.' }, { quoted: m })
      return
    }

    const typeName = Object.keys(targetMessage)[0] || 'unknown'
    const raw      = JSON.stringify(targetMessage, null, 2)

    const isInteractive =
      raw.includes('"interactiveMessage"') ||
      raw.includes('"nativeFlowMessage"')

    const additionalNodes = isInteractive
      ? `,
  additionalNodes: [{
    tag: "biz", attrs: {},
    content: [{
      tag: "interactive", attrs: { type: "native_flow", v: "1" },
      content: [{ tag: "native_flow", attrs: { v: "9", name: "mixed" } }]
    }]
  }]`
      : ''

    const jsContent = `// Generated by Lumi Hevia CRM
// Type: ${typeName}

const rawContent = ${raw}

const content = reviveBuffers(rawContent)

await sock.relayMessage(jid, content, {
  messageId: "LH" + Date.now()${additionalNodes}
})
`

    const buf   = Buffer.from(jsContent, 'utf-8')
    const rand  = Math.random().toString(36).slice(2, 7)
    const fname = `${typeName}-${rand}.js`

    await sock.sendMessage(chat, {
      document: buf,
      mimetype: 'application/javascript',
      fileName: fname,
      caption: [
        `*[ CRM ]*`,
        ``,
        `Type  : ${typeName}`,
        `File  : ${fname}`,
        ``,
        `Reply file ini lalu ketik *run* untuk eksekusi.`,
      ].join('\n'),
    }, { quoted: m })
  },
}
